// <auto-generated />
using System;
using Main.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityAppDbContext))]
    [Migration("20260911193218_InitialCreateIdentity31")]
    partial class InitialCreateIdentity31
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Main.Model.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000003-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e688567b-42b4-4ee4-8f01-d0002e334cee",
                            Email = "admin@system.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMOyS2QF+2L15yOnjA9jZp8M+QJhdH0/fKpGF1gd+6x0Fe6iXgaiuLWqB0Nj3VlIzQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6b8d2d60-26b3-4965-b4a8-da1fd22b77c8",
                            TwoFactorEnabled = false,
                            UserName = "admin@system.com"
                        },
                        new
                        {
                            Id = "00000004-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6ed1a8e6-ec1b-4001-a20c-cfde693ecd2b",
                            Email = "tenant1.admin@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAELxUQ0R/68QrKx2f+u1GFdLoou93VJ2StBTa8GQi2rDVZIMe1RD+MOB3kBz2Airzqg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bc970dec-b138-43e7-8a61-d1911874b2c1",
                            TwoFactorEnabled = false,
                            UserName = "tenant1.admin@test.com"
                        },
                        new
                        {
                            Id = "00000005-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "01825c7f-83d7-4313-a924-51f5065fca47",
                            Email = "tenant1.manager@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEB/seyuHyBJ3XSTFDUwIyBZXGjFNCzWxoG3KwAeCR2ryRkHoM/LlElU1RpqLO2jQvg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "61d990c3-4cdc-4153-acbe-26e978bd2157",
                            TwoFactorEnabled = false,
                            UserName = "tenant1.manager@test.com"
                        },
                        new
                        {
                            Id = "00000006-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1caaae72-7417-4110-a3ae-4ffcfab471d2",
                            Email = "tenant1.member@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEIZ2YTF8yOB5gLUgqPesK2P2EZUIdZDHr0Og2YUgvFtftA8IgTKmnZFjN8hNLBBKoQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23d51ad4-5e12-4c24-96ec-d00531314c83",
                            TwoFactorEnabled = false,
                            UserName = "tenant1.member@test.com"
                        },
                        new
                        {
                            Id = "00000007-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "22b7ec05-6e1d-47fd-b7f7-a3fad81f6b3d",
                            Email = "tenant2.admin@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEBNeA+i9X/m3qPmn1RtKkGjh53aA1BvckGFBOOMKli4eE5Ci1L5IM+oYQKNHT5OFTw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d895dfdc-ef90-46b4-8c12-27f51abc3b67",
                            TwoFactorEnabled = false,
                            UserName = "tenant2.admin@test.com"
                        },
                        new
                        {
                            Id = "00000008-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e58ff810-e76f-404b-9686-1abc8e6b155f",
                            Email = "tenant2.manager@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEAjfPUQax6y535Ewsj0sp1YXNKg15W0r0WBBy2ptxdA1reyww0zq0otCI2kkmsvWjA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4a00716b-b27a-45f9-81d5-9b9ff470dcfe",
                            TwoFactorEnabled = false,
                            UserName = "tenant2.manager@test.com"
                        },
                        new
                        {
                            Id = "00000009-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9b920ba-c003-4723-904d-2880604fd8e5",
                            Email = "tenant2.member@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAENAs8foQg49AMTbX73V2zuYGWinPZjyuGES5gaHMJE0VeV6SnADI89PC4BRG2uJh+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7a68c69d-9992-497f-9141-0895ab3268ee",
                            TwoFactorEnabled = false,
                            UserName = "tenant2.member@test.com"
                        },
                        new
                        {
                            Id = "0000000a-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7982e360-5a8a-41cc-a707-7424b6ff6817",
                            Email = "finearts@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEFBwJeLAi+XquqcyIUJgXGUADDQm3A/lzq5s+tpyYUwbIFmFBJKeQtvthRmRVX7KeQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "845e4085-dd2e-49f1-8c0f-ad988c0fd2ab",
                            TwoFactorEnabled = false,
                            UserName = "finearts@test.com"
                        },
                        new
                        {
                            Id = "0000000b-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c5074fb5-80b6-4b70-95d9-bebe863f172c",
                            Email = "lifestyles@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEDD8A78kFSaf8wr9Bon661smKx1xhboig+74zqgC2snvulQjTy8Zr4G6vkoZeIAXZQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b214ce2c-af1a-4dd4-a68b-403335cc38f8",
                            TwoFactorEnabled = false,
                            UserName = "lifestyles@test.com"
                        });
                });

            modelBuilder.Entity("Main.Model.Identity.EmailOutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedOnUtc")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RetryCount")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmailOutboxMessage");
                });

            modelBuilder.Entity("Main.Model.Identity.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HostType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreType")
                        .HasColumnType("int");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            Host = "tenant1",
                            HostType = 1,
                            IsActive = true,
                            StoreType = 6,
                            TenantContinent = "Asia",
                            TenantCountry = 1,
                            TenantName = "Tenant 1 (Finearts: Collections)"
                        },
                        new
                        {
                            TenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            Host = "tenant2",
                            HostType = 1,
                            IsActive = true,
                            StoreType = 5,
                            TenantContinent = "Asia",
                            TenantCountry = 1,
                            TenantName = "Tenant 2 (Finearts: Crafts)"
                        },
                        new
                        {
                            TenantId = new Guid("00000011-0000-0000-0000-000000000000"),
                            Host = "finearts",
                            HostType = 1,
                            IsActive = true,
                            StoreType = 2,
                            TenantContinent = "Asia",
                            TenantCountry = 1,
                            TenantName = "Tenant 3 (Finearts: Arts)"
                        },
                        new
                        {
                            TenantId = new Guid("00000012-0000-0000-0000-000000000000"),
                            Host = "lifestyles",
                            HostType = 1,
                            IsActive = true,
                            StoreType = 1,
                            TenantContinent = "Asia",
                            TenantCountry = 1,
                            TenantName = "Tenant 4 (LifeStyles)"
                        });
                });

            modelBuilder.Entity("Main.Model.Identity.TenantInvitation", b =>
                {
                    b.Property<Guid>("InviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvitedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InviteId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantInvitations");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantSmtpServer", b =>
                {
                    b.Property<int>("SmtpServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SmtpServerId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SmtpEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpHostServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SmtpServerId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantSmtpServers");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantTheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyBackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonBGBorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FontStack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoRelativeFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuBackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuItemHoverBGColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuItemHoverColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantThemes");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantUserRole", b =>
                {
                    b.Property<int>("TenantUserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantUserRoleId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TenantUserRoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("TenantUserRoles");

                    b.HasData(
                        new
                        {
                            TenantUserRoleId = 2,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantRole = "Admin",
                            UserId = "00000004-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 3,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantRole = "Manager",
                            UserId = "00000005-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 4,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantRole = "Member",
                            UserId = "00000006-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 5,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantRole = "Admin",
                            UserId = "00000007-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 6,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantRole = "Manager",
                            UserId = "00000008-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 7,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantRole = "Member",
                            UserId = "00000009-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 8,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000011-0000-0000-0000-000000000000"),
                            TenantRole = "Admin",
                            UserId = "0000000a-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 9,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000012-0000-0000-0000-000000000000"),
                            TenantRole = "Admin",
                            UserId = "0000000b-0000-0000-0000-000000000000"
                        });
                });

            modelBuilder.Entity("Main.Model.Identity.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("TenantContinent")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TenantCountry")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("ApplicationUserRefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000013-0000-0000-0000-000000000000",
                            Name = "GlobalAdmin",
                            NormalizedName = "GLOBALADMIN"
                        },
                        new
                        {
                            Id = "00000014-0000-0000-0000-000000000000",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "00000003-0000-0000-0000-000000000000",
                            RoleId = "00000013-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "00000004-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "00000005-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "00000006-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "00000007-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "00000008-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "00000009-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "0000000a-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "0000000b-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Main.Model.Identity.TenantInvitation", b =>
                {
                    b.HasOne("Main.Model.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantSmtpServer", b =>
                {
                    b.HasOne("Main.Model.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantTheme", b =>
                {
                    b.HasOne("Main.Model.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantUserRole", b =>
                {
                    b.HasOne("Main.Model.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Model.Identity.ApplicationUser", "User")
                        .WithMany("TenantUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Main.Model.Identity.UserRefreshToken", b =>
                {
                    b.HasOne("Main.Model.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Model.Identity.ApplicationUser", "User")
                        .WithMany("UserRefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Main.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Main.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Main.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Model.Identity.ApplicationUser", b =>
                {
                    b.Navigation("TenantUsers");

                    b.Navigation("UserRefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
