// <auto-generated />
using System;
using Main.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620232718_InitialApplicationDBMigration2")]
    partial class InitialApplicationDBMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("ApplicationRoles");

                    b.HasData(
                        new
                        {
                            Id = "e02fd0e4-00fd-090a-ca30-0d00a0038ba0",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            Id = "e02fd0e4-00fd-090a-ca30-0d00a0038ba4",
                            Name = "User",
                            NormalizedName = "USER",
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            Id = "e02fd0e4-00fd-090a-ca30-0F00a0898ba4",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN",
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            Id = "d02fd0e4-10fd-090a-ca30-0d00a0038ba0",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        },
                        new
                        {
                            Id = "d02fd0e4-20fd-090a-ca30-0d00a0038ba4",
                            Name = "User",
                            NormalizedName = "USER",
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        },
                        new
                        {
                            Id = "d02fd0e4-30fd-090a-ca30-0F00a0898ba4",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN",
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        });
                });

            modelBuilder.Entity("Domain.Model.AValue", b =>
                {
                    b.Property<long>("ValueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ValueID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ParentValueId")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Variable")
                        .HasColumnType("int");

                    b.HasKey("ValueID");

                    b.ToTable("AValue");
                });

            modelBuilder.Entity("Domain.Model.AdminImageFile", b =>
                {
                    b.Property<int>("AdminImageFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminImageFileID"));

                    b.Property<int>("AdminPostID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageFileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminImageFileID");

                    b.HasIndex("AdminPostID");

                    b.ToTable("AdImageFiles");
                });

            modelBuilder.Entity("Domain.Model.AdminPost", b =>
                {
                    b.Property<int>("AdminPostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminPostID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.Property<string>("PosterContactNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PosterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortNote")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminPostID");

                    b.ToTable("AdPosts");
                });

            modelBuilder.Entity("Domain.Model.AdminPostComment", b =>
                {
                    b.Property<int>("AdminPostCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminPostCommentID"));

                    b.Property<int>("AdminPostID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminPostCommentID");

                    b.HasIndex("AdminPostID");

                    b.ToTable("AdPostComments");
                });

            modelBuilder.Entity("Domain.Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("ApplicationUsers");

                    b.HasData(
                        new
                        {
                            Id = "e03fd0d4-00fd-090a-ca10-0d00a1118ba4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e1aab437-90e4-4824-95a7-67463514ddec",
                            Email = "naimul.prodhan@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NAIMUL.PRODHAN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN1",
                            PasswordHash = "AQAAAAIAAYagAAAAEOMJXMujdrLC+r3kbLELt+P+kw1Qlio+VseW4FhhKE1mS26b0/4wGbFeDGdQLDh/3Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aab94157-51a8-4c7b-9ca6-25d87bd5f524",
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0",
                            TwoFactorEnabled = false,
                            UserName = "SuperAdmin1"
                        },
                        new
                        {
                            Id = "e03fd0d4-00fd-090a-da10-0d00a2228ba4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33885a1a-b48a-4853-8c54-fa6aad7fe8b1",
                            Email = "naimul.prodhan@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NAIMUL.PRODHAN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN2",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxUXGcxy47UuLPQDZy98UQZrSVgPm9IPyM4pqmfdd6zr8LWEWtpNKikwBYv0q0b2g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1409d254-f4c3-4f2e-845d-cfd118287f79",
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0",
                            TwoFactorEnabled = false,
                            UserName = "SuperAdmin2"
                        },
                        new
                        {
                            Id = "e03fd0e4-00fd-090a-ca10-0d00a0018ba4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "49f2575f-1b2b-47c4-8043-788892033f94",
                            Email = "syedron@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SYEDRON@GMAIL.COM",
                            NormalizedUserName = "ADMIN1",
                            PasswordHash = "AQAAAAIAAYagAAAAEIukdmRxR3plqqMyk3kSYJSaq6CGigj7YfmPujshYDadBd4JJEzZrlajwduM/GH6Qw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fcc1cb69-f046-4082-9987-07dfd5a7479a",
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0",
                            TwoFactorEnabled = false,
                            UserName = "Admin1"
                        },
                        new
                        {
                            Id = "e03fd0e4-55fd-095a-ca10-0d00a0018ba4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d4d67c2-4400-448d-9cb0-8a99ce93ea79",
                            Email = "syedron@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SYEDRON@GMAIL.COM",
                            NormalizedUserName = "ADMIN2",
                            PasswordHash = "AQAAAAIAAYagAAAAEKzd+DhKaamQwyxHhnY83NQ1wZE3oiMe6we0keFh0qN1Doin0LAkwn0jrmeTdAoEUg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c2cc0957-f84a-478c-92eb-3d1342c15897",
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0",
                            TwoFactorEnabled = false,
                            UserName = "Admin2"
                        });
                });

            modelBuilder.Entity("Domain.Model.Page", b =>
                {
                    b.Property<int>("PageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnumPublicPage")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageID");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            PageID = 1,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 1,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            PageID = 2,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 3,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            PageID = 3,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 12,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            PageID = 4,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 11,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            PageID = 5,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 2,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            PageID = 6,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 7,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            PageID = 7,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 6,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            PageID = 8,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 9,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            PageID = 9,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 10,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            PageID = 10,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 8,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0"
                        },
                        new
                        {
                            PageID = 11,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 1,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        },
                        new
                        {
                            PageID = 12,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 3,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        },
                        new
                        {
                            PageID = 13,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 12,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        },
                        new
                        {
                            PageID = 14,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 11,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        },
                        new
                        {
                            PageID = 15,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 2,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        },
                        new
                        {
                            PageID = 16,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 7,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        },
                        new
                        {
                            PageID = 17,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 6,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        },
                        new
                        {
                            PageID = 18,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 9,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        },
                        new
                        {
                            PageID = 19,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 10,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        },
                        new
                        {
                            PageID = 20,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 8,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0"
                        });
                });

            modelBuilder.Entity("Domain.Model.Panel", b =>
                {
                    b.Property<int>("PanelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PanelID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageID")
                        .HasColumnType("int");

                    b.Property<int>("PanelPosition")
                        .HasColumnType("int");

                    b.Property<int>("PanelTemplate")
                        .HasColumnType("int");

                    b.Property<string>("PanelTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PanelID");

                    b.HasIndex("PageID");

                    b.ToTable("Panels");
                });

            modelBuilder.Entity("Domain.Model.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnumPostType")
                        .HasColumnType("int");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PanelID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RootID")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostID");

                    b.HasIndex("PanelID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Domain.Model.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SaleCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SearchTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Model.ProductComment", b =>
                {
                    b.Property<int>("ProductCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCommentID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductCommentID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductComments");
                });

            modelBuilder.Entity("Domain.Model.ProductImageFile", b =>
                {
                    b.Property<int>("ProductImageFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageFileID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageFileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductImageFileID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductImageFiles");
                });

            modelBuilder.Entity("Domain.Model.Tenant", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopType")
                        .HasColumnType("int");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = "e02fd0e1-00fd-009a-ca30-0d00a2345ba0",
                            Domain = "fanarts-local",
                            Name = "Fine Arts Store",
                            ShopType = 2
                        },
                        new
                        {
                            TenantId = "e02fd0e1-00fd-008a-ca30-5d00a5242ba0",
                            Domain = "lifestyle-local",
                            Name = "LifeStyle Store",
                            ShopType = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("IdentityUserRole<string>");

                    b.HasData(
                        new
                        {
                            UserId = "e03fd0d4-00fd-090a-ca10-0d00a1118ba4",
                            RoleId = "e02fd0e4-00fd-090a-ca30-0F00a0898ba4"
                        },
                        new
                        {
                            UserId = "e03fd0d4-00fd-090a-da10-0d00a2228ba4",
                            RoleId = "d02fd0e4-30fd-090a-ca30-0F00a0898ba4"
                        },
                        new
                        {
                            UserId = "e03fd0e4-00fd-090a-ca10-0d00a0018ba4",
                            RoleId = "e02fd0e4-00fd-090a-ca30-0d00a0038ba0"
                        },
                        new
                        {
                            UserId = "e03fd0e4-55fd-095a-ca10-0d00a0018ba4",
                            RoleId = "d02fd0e4-10fd-090a-ca30-0d00a0038ba0"
                        });
                });

            modelBuilder.Entity("Domain.Model.AdminImageFile", b =>
                {
                    b.HasOne("Domain.Model.AdminPost", "AdminPost")
                        .WithMany("ListAdminImageFiles")
                        .HasForeignKey("AdminPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminPost");
                });

            modelBuilder.Entity("Domain.Model.AdminPostComment", b =>
                {
                    b.HasOne("Domain.Model.AdminPost", "AdminPost")
                        .WithMany("ListAdminPostComments")
                        .HasForeignKey("AdminPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminPost");
                });

            modelBuilder.Entity("Domain.Model.Panel", b =>
                {
                    b.HasOne("Domain.Model.Page", "Page")
                        .WithMany("ListPanels")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Domain.Model.Post", b =>
                {
                    b.HasOne("Domain.Model.Panel", "Panel")
                        .WithMany("ListPosts")
                        .HasForeignKey("PanelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("Domain.Model.ProductComment", b =>
                {
                    b.HasOne("Domain.Model.Product", "Product")
                        .WithMany("ListComments")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Model.ProductImageFile", b =>
                {
                    b.HasOne("Domain.Model.Product", "Product")
                        .WithMany("ListImageFiles")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Model.AdminPost", b =>
                {
                    b.Navigation("ListAdminImageFiles");

                    b.Navigation("ListAdminPostComments");
                });

            modelBuilder.Entity("Domain.Model.Page", b =>
                {
                    b.Navigation("ListPanels");
                });

            modelBuilder.Entity("Domain.Model.Panel", b =>
                {
                    b.Navigation("ListPosts");
                });

            modelBuilder.Entity("Domain.Model.Product", b =>
                {
                    b.Navigation("ListComments");

                    b.Navigation("ListImageFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
