// <auto-generated />
using System;
using Main.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Infrastructure.Data.Migrations.Business
{
    [DbContext(typeof(BussinessAppDbContext))]
    [Migration("20260611225425_InitialBusinessMigration2")]
    partial class InitialBusinessMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.AdminImageFile", b =>
                {
                    b.Property<int>("AdminImageFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminImageFileID"));

                    b.Property<int>("AdminPostID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageFileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AdminImageFileID");

                    b.HasIndex("AdminPostID");

                    b.ToTable("AdImageFiles");
                });

            modelBuilder.Entity("Domain.Model.AdminPost", b =>
                {
                    b.Property<int>("AdminPostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminPostID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.Property<string>("PosterContactNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PosterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortNote")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminPostID");

                    b.ToTable("AdPosts");
                });

            modelBuilder.Entity("Domain.Model.AdminPostComment", b =>
                {
                    b.Property<int>("AdminPostCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminPostCommentID"));

                    b.Property<int>("AdminPostID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AdminPostCommentID");

                    b.HasIndex("AdminPostID");

                    b.ToTable("AdPostComments");
                });

            modelBuilder.Entity("Domain.Model.Page", b =>
                {
                    b.Property<int>("PageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnumPublicPage")
                        .HasColumnType("int");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PageID");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            PageID = 1,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 1,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 2,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 3,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 3,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 12,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 4,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 11,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 5,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 2,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 6,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 7,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 8,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 6,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 9,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 9,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 11,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 10,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 12,
                            CreatedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 8,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserId = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            IsActive = true,
                            ModifiedBy = "e02fd0e4-00fd-000a-ca30-0F00a0898ba1",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Model.Panel", b =>
                {
                    b.Property<int>("PanelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PanelID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageID")
                        .HasColumnType("int");

                    b.Property<int>("PanelPosition")
                        .HasColumnType("int");

                    b.Property<int>("PanelTemplate")
                        .HasColumnType("int");

                    b.Property<string>("PanelTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PanelID");

                    b.HasIndex("PageID");

                    b.ToTable("Panels");
                });

            modelBuilder.Entity("Domain.Model.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnumPostType")
                        .HasColumnType("int");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PanelID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RootID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostID");

                    b.HasIndex("PanelID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Domain.Model.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SaleCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SearchTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Model.ProductComment", b =>
                {
                    b.Property<int>("ProductCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCommentID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("ProductCommentID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductComments");
                });

            modelBuilder.Entity("Domain.Model.ProductImageFile", b =>
                {
                    b.Property<int>("ProductImageFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageFileID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageFileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("ProductImageFileID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductImageFiles");
                });

            modelBuilder.Entity("Domain.Model.AdminImageFile", b =>
                {
                    b.HasOne("Domain.Model.AdminPost", "AdminPost")
                        .WithMany("ListAdminImageFiles")
                        .HasForeignKey("AdminPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminPost");
                });

            modelBuilder.Entity("Domain.Model.AdminPostComment", b =>
                {
                    b.HasOne("Domain.Model.AdminPost", "AdminPost")
                        .WithMany("ListAdminPostComments")
                        .HasForeignKey("AdminPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminPost");
                });

            modelBuilder.Entity("Domain.Model.Panel", b =>
                {
                    b.HasOne("Domain.Model.Page", "Page")
                        .WithMany("ListPanels")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Domain.Model.Post", b =>
                {
                    b.HasOne("Domain.Model.Panel", "Panel")
                        .WithMany("ListPosts")
                        .HasForeignKey("PanelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("Domain.Model.ProductComment", b =>
                {
                    b.HasOne("Domain.Model.Product", "Product")
                        .WithMany("ListComments")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Model.ProductImageFile", b =>
                {
                    b.HasOne("Domain.Model.Product", "Product")
                        .WithMany("ListImageFiles")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Model.AdminPost", b =>
                {
                    b.Navigation("ListAdminImageFiles");

                    b.Navigation("ListAdminPostComments");
                });

            modelBuilder.Entity("Domain.Model.Page", b =>
                {
                    b.Navigation("ListPanels");
                });

            modelBuilder.Entity("Domain.Model.Panel", b =>
                {
                    b.Navigation("ListPosts");
                });

            modelBuilder.Entity("Domain.Model.Product", b =>
                {
                    b.Navigation("ListComments");

                    b.Navigation("ListImageFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
