// <auto-generated />
using System;
using Main.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Infrastructure.Data.Migrations.Business
{
    [DbContext(typeof(BussinessAppDbContext))]
    partial class BussinessAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.AValue", b =>
                {
                    b.Property<long>("ValueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ValueID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ParentValueId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Variable")
                        .HasColumnType("int");

                    b.HasKey("ValueID");

                    b.ToTable("AValues");
                });

            modelBuilder.Entity("Domain.Model.AdminImageFile", b =>
                {
                    b.Property<int>("AdminImageFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminImageFileID"));

                    b.Property<int>("AdminPostID")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageFileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("AdminImageFileID");

                    b.HasIndex("AdminPostID");

                    b.ToTable("AdminImageFiles");
                });

            modelBuilder.Entity("Domain.Model.AdminPost", b =>
                {
                    b.Property<int>("AdminPostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminPostID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.Property<string>("PosterContactNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PosterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminPostID");

                    b.HasIndex("UserID");

                    b.ToTable("AdminPosts");
                });

            modelBuilder.Entity("Domain.Model.AdminPostComment", b =>
                {
                    b.Property<int>("AdminPostCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminPostCommentID"));

                    b.Property<int>("AdminPostID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminPostCommentID");

                    b.HasIndex("AdminPostID");

                    b.ToTable("AdminPostComments");
                });

            modelBuilder.Entity("Domain.Model.Page", b =>
                {
                    b.Property<int>("PageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnumPublicPage")
                        .HasColumnType("int");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PageID");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            PageID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 1,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IsActive = true,
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 3,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IsActive = true,
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 3,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 12,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IsActive = true,
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 4,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 11,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IsActive = true,
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 5,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 2,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IsActive = true,
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 6,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 7,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IsActive = true,
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 8,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 6,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IsActive = true,
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 9,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 9,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IsActive = true,
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 11,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 10,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IsActive = true,
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PageID = 12,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnumPublicPage = 8,
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IsActive = true,
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Model.PageContent", b =>
                {
                    b.Property<int>("PageContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageContentID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageID")
                        .HasColumnType("int");

                    b.HasKey("PageContentID");

                    b.HasIndex("PageID");

                    b.ToTable("PageContents");
                });

            modelBuilder.Entity("Domain.Model.PagePanel", b =>
                {
                    b.Property<int>("PanelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PanelID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageContentID")
                        .HasColumnType("int");

                    b.Property<int>("PanelPosition")
                        .HasColumnType("int");

                    b.Property<int>("PanelTemplate")
                        .HasColumnType("int");

                    b.Property<string>("PanelTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PanelID");

                    b.HasIndex("PageContentID");

                    b.ToTable("PagePanels");
                });

            modelBuilder.Entity("Domain.Model.PanelPost", b =>
                {
                    b.Property<int>("PanelPostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PanelPostID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnumPostType")
                        .HasColumnType("int");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageFileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PanelID")
                        .HasColumnType("int");

                    b.Property<string>("PostDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostOrder")
                        .HasColumnType("int");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RootID")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PanelPostID");

                    b.HasIndex("PanelID");

                    b.ToTable("PanelPosts");
                });

            modelBuilder.Entity("Domain.Model.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SaleCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SearchTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Model.ProductComment", b =>
                {
                    b.Property<int>("ProductCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCommentID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("ProductCommentID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductComments");
                });

            modelBuilder.Entity("Domain.Model.ProductImageFile", b =>
                {
                    b.Property<int>("ProductImageFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageFileID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageFileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("ProductImageFileID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductImageFiles");
                });

            modelBuilder.Entity("Domain.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<double?>("AccountBalance")
                        .HasColumnType("float");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HostCompanyName")
                        .HasColumnType("int");

                    b.Property<int>("HostCountry")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAccountType")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            ClientName = "Developer",
                            CreatedBy = 2147483647,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "naimul.prodhan@gmail.com",
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserID = "e03fd0d4-00fd-090a-ca10-0d00a1118ba4",
                            IsActive = true,
                            ModifiedBy = 2147483647,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserAccountType = 0
                        },
                        new
                        {
                            UserID = 2,
                            ClientName = "FineArts",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "syedron@gmail.com",
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserID = "e03fd0e4-00fd-090a-ca10-0d00a0018ba4",
                            IsActive = true,
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserAccountType = 0
                        },
                        new
                        {
                            UserID = 3,
                            ClientName = "Fine Arts",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "finearts@gmail.com",
                            HostCompanyName = 2,
                            HostCountry = 1,
                            IdentityUserID = "e03fd0e4-00fd-090a-ca10-0d00a0018ba5",
                            IsActive = true,
                            ModifiedBy = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserAccountType = 0
                        });
                });

            modelBuilder.Entity("Domain.Model.AdminImageFile", b =>
                {
                    b.HasOne("Domain.Model.AdminPost", "AdminPost")
                        .WithMany("ListAdminImageFiles")
                        .HasForeignKey("AdminPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminPost");
                });

            modelBuilder.Entity("Domain.Model.AdminPost", b =>
                {
                    b.HasOne("Domain.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Model.AdminPostComment", b =>
                {
                    b.HasOne("Domain.Model.AdminPost", "AdminPost")
                        .WithMany("ListAdminPostComments")
                        .HasForeignKey("AdminPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminPost");
                });

            modelBuilder.Entity("Domain.Model.PageContent", b =>
                {
                    b.HasOne("Domain.Model.Page", "Page")
                        .WithMany("ListPageContents")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Domain.Model.PagePanel", b =>
                {
                    b.HasOne("Domain.Model.PageContent", "PageContent")
                        .WithMany("ListPagePanels")
                        .HasForeignKey("PageContentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageContent");
                });

            modelBuilder.Entity("Domain.Model.PanelPost", b =>
                {
                    b.HasOne("Domain.Model.PagePanel", "PagePanel")
                        .WithMany("ListPanelPosts")
                        .HasForeignKey("PanelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PagePanel");
                });

            modelBuilder.Entity("Domain.Model.Product", b =>
                {
                    b.HasOne("Domain.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Model.ProductComment", b =>
                {
                    b.HasOne("Domain.Model.Product", "Product")
                        .WithMany("ListComments")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Model.ProductImageFile", b =>
                {
                    b.HasOne("Domain.Model.Product", "Product")
                        .WithMany("ListImageFiles")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Model.AdminPost", b =>
                {
                    b.Navigation("ListAdminImageFiles");

                    b.Navigation("ListAdminPostComments");
                });

            modelBuilder.Entity("Domain.Model.Page", b =>
                {
                    b.Navigation("ListPageContents");
                });

            modelBuilder.Entity("Domain.Model.PageContent", b =>
                {
                    b.Navigation("ListPagePanels");
                });

            modelBuilder.Entity("Domain.Model.PagePanel", b =>
                {
                    b.Navigation("ListPanelPosts");
                });

            modelBuilder.Entity("Domain.Model.Product", b =>
                {
                    b.Navigation("ListComments");

                    b.Navigation("ListImageFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
