// <auto-generated />
using System;
using Main.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Infrastructure.Migrations.TenantDb
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260911191224_InitialCreateTenant30")]
    partial class InitialCreateTenant30
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Main.Model.Identity.Page", b =>
                {
                    b.Property<int>("PageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageID"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnumPublicPage")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.HasKey("PageID");

                    b.HasIndex("MyTenantId");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            PageID = 2,
                            EnumPublicPage = 1,
                            IsActive = true,
                            MyTenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 3,
                            EnumPublicPage = 3,
                            IsActive = true,
                            MyTenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 4,
                            EnumPublicPage = 8,
                            IsActive = true,
                            MyTenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 5,
                            EnumPublicPage = 4,
                            IsActive = true,
                            MyTenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 6,
                            EnumPublicPage = 5,
                            IsActive = true,
                            MyTenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 7,
                            EnumPublicPage = 6,
                            IsActive = true,
                            MyTenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 8,
                            EnumPublicPage = 2,
                            IsActive = true,
                            MyTenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 9,
                            EnumPublicPage = 7,
                            IsActive = true,
                            MyTenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 11,
                            EnumPublicPage = 1,
                            IsActive = true,
                            MyTenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 12,
                            EnumPublicPage = 3,
                            IsActive = true,
                            MyTenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 13,
                            EnumPublicPage = 8,
                            IsActive = true,
                            MyTenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 14,
                            EnumPublicPage = 4,
                            IsActive = true,
                            MyTenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 15,
                            EnumPublicPage = 5,
                            IsActive = true,
                            MyTenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 16,
                            EnumPublicPage = 6,
                            IsActive = true,
                            MyTenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 17,
                            EnumPublicPage = 2,
                            IsActive = true,
                            MyTenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        },
                        new
                        {
                            PageID = 18,
                            EnumPublicPage = 7,
                            IsActive = true,
                            MyTenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantCountry = 1
                        });
                });

            modelBuilder.Entity("Main.Model.Tenant.AdminImageFile", b =>
                {
                    b.Property<int>("AdminImageFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminImageFileID"));

                    b.Property<int>("AdminPostID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageFileContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.HasKey("AdminImageFileID");

                    b.HasIndex("AdminPostID");

                    b.HasIndex("MyTenantId");

                    b.ToTable("AdminImageFiles");
                });

            modelBuilder.Entity("Main.Model.Tenant.AdminPost", b =>
                {
                    b.Property<int>("AdminPostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminPostID"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.Property<string>("PosterContactNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PosterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortNote")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminPostID");

                    b.HasIndex("MyTenantId");

                    b.ToTable("AdminPosts");
                });

            modelBuilder.Entity("Main.Model.Tenant.AdminPostComment", b =>
                {
                    b.Property<int>("AdminPostCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminPostCommentID"));

                    b.Property<int>("AdminPostID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.HasKey("AdminPostCommentID");

                    b.HasIndex("AdminPostID");

                    b.HasIndex("MyTenantId");

                    b.ToTable("AdminPostComments");
                });

            modelBuilder.Entity("Main.Model.Tenant.AllowedValue", b =>
                {
                    b.Property<long>("ValueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ValueID"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ParentValueId")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Variable")
                        .HasColumnType("int");

                    b.HasKey("ValueID");

                    b.HasIndex("MyTenantId");

                    b.ToTable("AllowedValues");
                });

            modelBuilder.Entity("Main.Model.Tenant.Panel", b =>
                {
                    b.Property<int>("PanelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PanelID"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PageID")
                        .HasColumnType("int");

                    b.Property<int?>("PanelPosition")
                        .HasColumnType("int");

                    b.Property<int>("PanelTemplate")
                        .HasColumnType("int");

                    b.Property<string>("PanelTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.HasKey("PanelID");

                    b.HasIndex("MyTenantId");

                    b.HasIndex("PageID");

                    b.ToTable("Panels");
                });

            modelBuilder.Entity("Main.Model.Tenant.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnumPostType")
                        .HasColumnType("int");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PanelID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RootID")
                        .HasColumnType("int");

                    b.Property<int?>("SubCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostID");

                    b.HasIndex("MyTenantId");

                    b.HasIndex("PanelID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Main.Model.Tenant.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SaleCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("MyTenantId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Main.Model.Tenant.ProductComment", b =>
                {
                    b.Property<int>("ProductCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCommentID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.HasKey("ProductCommentID");

                    b.HasIndex("MyTenantId");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductComments");
                });

            modelBuilder.Entity("Main.Model.Tenant.ProductImageFile", b =>
                {
                    b.Property<int>("ProductImageFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageFileID"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MyTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.HasKey("ProductImageFileID");

                    b.HasIndex("MyTenantId");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductImageFiles");
                });

            modelBuilder.Entity("Main.Model.Tenant.AdminImageFile", b =>
                {
                    b.HasOne("Main.Model.Tenant.AdminPost", "AdminPost")
                        .WithMany("ListAdminImageFiles")
                        .HasForeignKey("AdminPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminPost");
                });

            modelBuilder.Entity("Main.Model.Tenant.AdminPostComment", b =>
                {
                    b.HasOne("Main.Model.Tenant.AdminPost", "AdminPost")
                        .WithMany("ListAdminPostComments")
                        .HasForeignKey("AdminPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminPost");
                });

            modelBuilder.Entity("Main.Model.Tenant.Panel", b =>
                {
                    b.HasOne("Main.Model.Identity.Page", "Page")
                        .WithMany("ListPanels")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Main.Model.Tenant.Post", b =>
                {
                    b.HasOne("Main.Model.Tenant.Panel", "Panel")
                        .WithMany("ListPosts")
                        .HasForeignKey("PanelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("Main.Model.Tenant.ProductComment", b =>
                {
                    b.HasOne("Main.Model.Tenant.Product", "Product")
                        .WithMany("ListComments")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Main.Model.Tenant.ProductImageFile", b =>
                {
                    b.HasOne("Main.Model.Tenant.Product", "Product")
                        .WithMany("ListImageFiles")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Main.Model.Identity.Page", b =>
                {
                    b.Navigation("ListPanels");
                });

            modelBuilder.Entity("Main.Model.Tenant.AdminPost", b =>
                {
                    b.Navigation("ListAdminImageFiles");

                    b.Navigation("ListAdminPostComments");
                });

            modelBuilder.Entity("Main.Model.Tenant.Panel", b =>
                {
                    b.Navigation("ListPosts");
                });

            modelBuilder.Entity("Main.Model.Tenant.Product", b =>
                {
                    b.Navigation("ListComments");

                    b.Navigation("ListImageFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
